# Generated by Django 3.0.7 on 2020-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://img.icons8.com/nolan/64/name.png', upload_to='profile_pics'),
        ),
    ]
