# Generated by Django 3.0.7 on 2020-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
