# Generated by Django 3.0.7 on 2020-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_feedback_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
